### ISSUE TITLE
[AppleScript] Suggested corrections

### ISSUE THREAD

**Issue by ChristoferK** [zenware/FizzBuzz#104]
https://github.com/zenware/FizzBuzz/blob/8d3279d25a563fbb24a3c16669d04872d112a0dc/applescript.applescript#L15-L20

The command line support is fine, although documentation is a bit lacking.  To send the output to `stdout` at any stage in the script's execution, you use the **`log`** command.  Line 15 can be deleted, and lines 17-19 can be replaced with:

<h3>

```applescript
log fizzbuzz(i) -- Print to stdout
```

</h3>

**Comment by nloveladyallen** [comment]
Done
