### ISSUE TITLE
Esoteric languages?

### ISSUE THREAD

**Issue by InvisibleRain** [zenware/FizzBuzz#98]
Hello! I want to add several esoteric languages such as "YoptaScript" and "~English". Are they allowed or this repository only for non-esoteric languages?

**Comment by zenware** [comment]
In my head it's only for non-esoteric languages, but I'm thinking about allowing esolangs as well...

**Comment by lucash-diskkun** [comment]
I too would like to see esoteric languages.

**Comment by zenware** [comment]
Okay, I’ve decided esolangs are allowed, however, they may need to come with a read me that explains how to run them, and perhaps key details of how they work, or a link to the documentation

**Comment by lucash-diskkun** [comment]
lovely, I suppose it is time for me to write fizzbuzz in whitespace now haha
